services:
  - type: web
    name: todo-api
    env: node
    plan: free
    region: singapore
    buildCommand: cd apps/api && npm install
    startCommand: cd apps/api && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        fromDatabase:
          name: todo-db
          property: connectionString
      - key: CORS_ORIGIN
        value: https://your-frontend.vercel.app

        