services:
  - type: web
    name: todo-api
    env: node
    region: singapore          # 离你近
    buildCommand: cd apps/api && npm install && npm run build
    startCommand: cd apps/api && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: CORS_ORIGIN
        sync: false




        