name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linux-lock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: rm -rf node_modules package-lock.json
      - run: npm install
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "fix: regenerate lock on linux"
